services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - DB_USER=backenduser
      - DB_PASS=superStrongPassword
      - DB_HOST=postgres
      - DB_PORT=5432 
      - DB_NAME=db
      - JWT_SECRET=strongTODO
    depends_on:
      migrations:
        condition: service_completed_successfully

  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=superStrongPassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432" # change this
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backenduser -d db"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres user=backenduser password=superStrongPassword dbname=db sslmode=disable
    volumes:
      - ./migrations:/migrations/
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:
